### ISSUE TITLE
Segmentation fault的問題

### ISSUE THREAD

**Issue by TOMxLEON** [compiler-f19/Discussion#110]
我程度不是很好，用pointer常常導致segmentation fault，請問有甚麼地方比較可能導致在SemanticAnalyzer.cpp全部的symbol table都印出來了但是回不到parser.y就segmentation fault了？
如果可以的話能不能請幫我看我前一次的commit？
https://github.com/compiler-f19/hw4-TOMxLEON
我目前把大部分的symbol table都建立好，還沒找semantic error。

**Comment by Naetw** [comment]
大概看了一下，你 `SymbolEntry` 裡面有成員的型別是指標，但我沒看到你有實作 `SymbolEntry` 的建構子，所以你基本上在使用 stack 上的殘渣，然後再對那個殘渣到處操作（相當於對 stack 亂寫）；再來你也沒實作 copy constructor，導致你在 push 的時候，其實是把殘渣也複製到 container 裡的元素內容去。

用 gdb 看，它是在 container stack 的解構子做到一半壞掉的，我不是很清楚 STL 的實作細節，但是看起來是它先 free 一塊記憶體之後，因為 glibc 的記憶體管理是會維護它內部的資料結構的，所以你 heap chunk 被 free 掉的時候它其實會對上面的內容作修改，修改成它維護所需要的資訊，而這個修改的動作把你某個東西寫爛了，導致後續對它 free 的時候直接 segmentation fault。

你可能會需要把每個你設計的資料結構的建構子、解構子設計好，然後若 container 的元素要使用 pointer type 的話，是你要負責把它做釋放。

**Comment by TOMxLEON** [comment]
請問要怎麼用gdb來debug來看segmentation fault在哪裡出問題？

**Comment by Naetw** [comment]
1. 發現有 segmentation fault

```
» ./parser ../test/test-cases/basic.p
[1]    8262 segmentation fault (core dumped)  ./parser ../test/test-cases/basic.p
```

2. 用 GDB 打開它

```
» gdb -q parser
Reading symbols from parser...done.
(gdb)
```

> -q 沒什麼意義，不加的話它會印一些 license 的東東。

3. 執行一次

```
(gdb) r ../test/test-cases/basic.p
Starting program: /tmp/parser ../test/test-cases/basic.p

Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x1940000012f) at malloc.c:3103
3103	malloc.c: No such file or directory.
(gdb)
```

4. 這時候可以用 back trace 來看看

```
(gdb) backtrace
#0  __GI___libc_free (mem=0x1940000012f) at malloc.c:3103
#1  0x0000000000408bc0 in __gnu_cxx::new_allocator<SymbolTable**>::deallocate (this=0x7fffffffe040,
    __p=0x1940000012f)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/ext/new_allocator.h:125
#2  0x0000000000408b90 in std::allocator_traits<std::allocator<SymbolTable**> >::deallocate (__a=...,
    __p=0x1940000012f, __n=8)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/alloc_traits.h:462
#3  0x0000000000408719 in std::_Deque_base<SymbolTable*, std::allocator<SymbolTable*> >::_M_deallocate_map (
    this=0x7fffffffe180, __p=0x1940000012f, __n=8)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_deque.h:623
#4  0x0000000000408ddc in std::_Deque_base<SymbolTable*, std::allocator<SymbolTable*> >::~_Deque_base (
    this=0x7fffffffe180)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_deque.h:667
#5  0x0000000000408cca in std::deque<SymbolTable*, std::allocator<SymbolTable*> >::~deque (this=0x7fffffffe180)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_deque.h:1045
#6  0x0000000000408c55 in std::stack<SymbolTable*, std::deque<SymbolTable*, std::allocator<SymbolTable*> > >::~stack (this=0x7fffffffe180)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_stack.h:99
#7  0x0000000000407e4a in SemanticAnalyzer::~SemanticAnalyzer (this=0x7fffffffe170)
    at include/semantic/SemanticAnalyzer.hpp:23
#8  0x0000000000407320 in dumpSymbolTable (node=0x642740) at parser.y:1154
#9  0x000000000040749c in main (argc=2, argv=0x7fffffffe328) at parser.y:1179
```

backtrace 指令會把目前程式的 call stack 狀態給印出來，一般來說你就可以知道你的程式是從哪邊執行到哪邊而發生問題，並且你也知道發生問題的是哪一行程式碼。但是你的問題是發生在 STL 的實作中，其實不是很好去 trace，建議就是從頭把建構子、解構子做好，因為目前的做法基本上一定會造成問題。

> backtrace 太長了，可以用 bt 這個縮寫取代

**另外，若要使用 GDB，記得在編譯的時候加上 -g 或是 -g3 來替你的執行檔加上 debug info，這樣在 GDB 所獲得的資訊會比較豐富，你也比較好看出問題在哪。**
